name : Context
on : push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.actor}}"
      - run: echo "${{github.run_id}}"
      - run: echo "${{github.workspace}}"
      - run: echo "${{github.repository}}"      